In [ ]:
scale transition rotation invariant

In [1]:
import torch

tensor_A = torch.tensor([[1, 2, 3], [4, 5 , 6]])
tensor_a = torch.broadcast(tensor_A, tensor_A)
print(tensor_a)

AttributeError: module 'torch' has no attribute 'broadcast'

In [3]:
import torch

tensor_x = torch.ones((2, 3), dtype = torch.float)
tensor_z = torch.ones((1, 3), dtype = torch.complex64)
tensor_z = tensor_x + tensor_z
print(tensor_x)
print(tensor_z.shape)
print(tensor_z.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
torch.complex64


In [4]:
import torch
x = [[20, 50, 70], [100, 110, 40]]
# convert x to tensor float64
print(torch.tensor(x, dtype = torch.float64))

tensor([[ 20.,  50.,  70.],
        [100., 110.,  40.]], dtype=torch.float64)


In [13]:
import torch 
print(torch.randint(5, (2, 2)))


tensor([[0, 3],
        [2, 0]])


In [14]:
import torch 
tennsor_x = torch.tensor([[[10, 20, 30, 40], [50, 60, 70, 80]], [[90, 100, 110, 120], [130, 140, 150, 160]]])
tennsor_x[..., -2, ...] = 0
print(tennsor_x)

tensor([[[ 10,  20,   0,  40],
         [ 50,  60,   0,  80]],

        [[ 90, 100,   0, 120],
         [130, 140,   0, 160]]])


In [ ]:
#initialize TPU
import torch_xla
import torch_xla.core.xla_model as xm
torch.xla_device("tpu")
torchx.schedulers.get_scheduler("tpu")
torch_xla.core.xla_model.xla_device()

In [16]:
torch.tensor([1, 2, 3], device=torch.device("cuda:0"))

tensor([1, 2, 3], device='cuda:0')

In [17]:
torch.tensor([1, 2, 3]).cuda()

tensor([1, 2, 3], device='cuda:0')

In [21]:
import torch_xla
torch_xla.core

ModuleNotFoundError: No module named 'torch_xla'

In [ ]:
import torch
from torch import nn

class RecurrentNet(nn.Module):
    def __init__(self):
        super().__init__()
        # shape of data is (a b c)
        self.rnn = nn.RNN(input_size = 1, hidden_size = 1, num_layers = 1, batch_first = True)
        self.out = nn.Linear(y, 1)

In [23]:
#find the norm of a matrix
torch.linalg.vector_norm

<function torch._C._linalg.linalg_vector_norm>

In [ ]:
#import multi dimension tensors
import torch
# what this does is 
import torch.utils

In [27]:
import torch 
tensor_A = torch.tensor([10, 20, 30, 40])
tensor_B = torch.tensor([1, 2, 3, 4])
product = tensor_A * tensor_B
print(product)
product = torch.mul(tensor_A, tensor_B)
print(product)
product = torch.multiply(tensor_A, tensor_B)
print(product)
tensor_A.mul(tensor_B)
print(tensor_A)

tensor([ 10,  40,  90, 160])
tensor([ 10,  40,  90, 160])
tensor([ 10,  40,  90, 160])
tensor([10, 20, 30, 40])


Comp vision

In [4]:
import tensorflow as tf

In [6]:
dataset = tf.data.Dataset.range(9)
dataset = dataset.window(5, shift =2, drop_remainder=True)
data_list = list()
for window in dataset:
    data_list.append(list(window.as_numpy_iterator()))
print(data_list)

[[0, 1, 2, 3, 4], [2, 3, 4, 5, 6], [4, 5, 6, 7, 8]]


2023-08-30 19:54:59.735726: W tensorflow/core/framework/dataset.cc:768] Input of Window will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.


In [ ]:
#convert into TFLite
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
tflite_model = tf.lite.TFLiteConverter.from_keras_model(model)

In [7]:
import tensorflow.numpy as tnp
ones = tnp.ones([1,1,2,2,3], dtype = float16)

ModuleNotFoundError: No module named 'tensorflow.numpy'

In [10]:
print(tf.constant([[[2,3]],[[4,5]]], dtype = tf.int16))

tf.Tensor(
[[[2 3]]

 [[4 5]]], shape=(2, 1, 2), dtype=int16)


In [12]:
a = tf.Variable([1,2,3], tf.TensorShape(None))

In [13]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import layers, Sequential
model = Sequential([
    keras.Input(shape=(100,)),
    layers.Dense(2, activation='relu', name = 'layer1'),
    layers.Dense(3, activation='relu', name = 'layer2'),
    layers.Dense(4, name = 'layer3'),

])
feature_extractor = keras.Model(inputs = model.input, outputs = model.layers[2].output)

In [14]:
import tensorflow as tf
import tensorflow.experimental.numpy as tnp
x = tf.math.count_nonzero(tnp.ones([3,3]))
y = tnp.count_nonzero(tf.ones([3,3]))
print(x)
print(y)

tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [15]:
import tensorflow
from tensorflow import keras
model = keras.Sequential([
    layers.Dense(2, activation='relu', name = 'layer1'),
    layers.Dense(3, activation='relu', name = 'layer2'),
    layers.Dense(4, name = 'layer3'),
])

model.compile(loss = keras.losses.SparseCategoricalCrossentropy(), optimizer = keras.optimizers.Adam(learning_rate=0.001), metrics=['accuracy'])

In [16]:
accuracy, loss = model.evaluate(x_test, y_test)

NameError: name 'x_test' is not defined

In [ ]:
model.compitle(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import layers, Sequential
model = Sequential()
model.add(layers.Bidirectional(layers.LSTM(32, return_sequences=True), input_shape=(None, 10)))